name: manage-azure-policy-c654f2af
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_amits-baseline_array_Windows_machines_should_meet_requirements_of_the_Azure_compute_security_baseline_azbaslineCount/**'
#      - .github/workflows/manage-azure-policy-c654f2af.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c654f2af}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_amits-baseline_array_Windows_machines_should_meet_requirements_of_the_Azure_compute_security_baseline_azbaslineCount/**
